# Generated by Django 5.1.5 on 2025-01-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
