# Generated by Django 5.1.6 on 2025-02-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0004_blogcomment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="timestamp",
            new_name="timeStamp",
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
