# Generated by Django 5.1.6 on 2025-02-11 10:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Blog", "0005_rename_timestamp_post_timestamp_alter_post_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="timeStamp",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
